version: "3.9"
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
  cmd:
    container_name: cmd
    build:
      context: ./command
      dockerfile: Dockerfile
    volumes:
      - ./command:/app/command
    ports:
      - "8888:8888"
